// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***SyDXIKrNYSELHRLuVCRpHmLxycEP7aIQc7E',
    appId: '1:443662973429:web:36d42cefcb0b036e16c8bc',
    messagingSenderId: '443662973429',
    projectId: 'bauwa-petcare',
    authDomain: 'bauwa-petcare.firebaseapp.com',
    storageBucket: 'bauwa-petcare.firebasestorage.app',
    measurementId: 'G-J6NZ3NDDPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***SyAFYB72ekCTBC29NCgbPUp-OBtJt5Lj8Pc',
    appId: '1:443662973429:android:5e1ce3229799849a16c8bc',
    messagingSenderId: '443662973429',
    projectId: 'bauwa-petcare',
    storageBucket: 'bauwa-petcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***SyCqgONdvulNQELbFcQWVemkbHctWlrbN1g',
    appId: '1:443662973429:ios:378a61b921f58ee216c8bc',
    messagingSenderId: '443662973429',
    projectId: 'bauwa-petcare',
    storageBucket: 'bauwa-petcare.firebasestorage.app',
    iosBundleId: 'com.example.bauwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***SyCqgONdvulNQELbFcQWVemkbHctWlrbN1g',
    appId: '1:443662973429:ios:378a61b921f58ee216c8bc',
    messagingSenderId: '443662973429',
    projectId: 'bauwa-petcare',
    storageBucket: 'bauwa-petcare.firebasestorage.app',
    iosBundleId: 'com.example.bauwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***SyDXIKrNYSELHRLuVCRpHmLxycEP7aIQc7E',
    appId: '1:443662973429:web:c0a5d02ae802c04116c8bc',
    messagingSenderId: '443662973429',
    projectId: 'bauwa-petcare',
    authDomain: 'bauwa-petcare.firebaseapp.com',
    storageBucket: 'bauwa-petcare.firebasestorage.app',
    measurementId: 'G-VSLL4VPRQZ',
  );
}
